#   Copyright 2026 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

SQL_SELECT_ORGANIZATION_DB = """
SELECT *
FROM T_ORGANIZATION_DB
"""

SQL_SELECT_WORKSPACE = """
SELECT *
FROM T_WORKSPACE
"""

# AI Conversation テーブル作成
CREATE_TABLE_AI_CONVERSATION = """
CREATE TABLE IF NOT EXISTS T_CHAT_CONVERSATION
(
  CONVERSATION_ID VARCHAR(36) NOT NULL COMMENT 'Conversation ID (ULID)',
  SERVICE_ID VARCHAR(64) NOT NULL COMMENT 'サービスID: AgenticAI/LLMEditor (システムプロンプト切り替え用)',
  WORKSPACE_ID VARCHAR(36) NOT NULL COMMENT 'Workspace ID',
  USER_ID VARCHAR(256) NOT NULL COMMENT 'Keycloak User ID',
  AI_SERVICE_ID VARCHAR(64) NOT NULL COMMENT 'AIサービスID: bedrock-cache, bedrock, openai, etc.',
  TITLE VARCHAR(255) NOT NULL COMMENT '会話タイトル',
  STATUS VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT 'ステータス: active/closed/archived',
  CURRENT_TOKEN_COUNT INT DEFAULT 0 COMMENT '現在のトークン数（累積）',
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  CREATE_USER VARCHAR(40) COMMENT '作成ユーザー',
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最終更新日時',
  LAST_UPDATE_USER VARCHAR(40) COMMENT '最終更新ユーザー',
  PRIMARY KEY (CONVERSATION_ID),
  INDEX IDX_SERVICE (SERVICE_ID),
  INDEX IDX_WORKSPACE_USER (WORKSPACE_ID, USER_ID),
  INDEX IDX_AI_SERVICE (AI_SERVICE_ID),
  INDEX IDX_STATUS (STATUS),
  INDEX IDX_LAST_UPDATE (LAST_UPDATE_TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIチャット会話'
"""

# AI Message テーブル作成
CREATE_TABLE_AI_MESSAGE = """
CREATE TABLE IF NOT EXISTS T_CHAT_MESSAGE
(
  MESSAGE_ID VARCHAR(36) NOT NULL COMMENT 'Message ID (ULID)',
  CONVERSATION_ID VARCHAR(36) NOT NULL COMMENT 'Conversation ID',
  MESSAGE_SEQ INT NOT NULL COMMENT 'メッセージ順序番号',
  CONTENTS LONGTEXT NOT NULL COMMENT 'コンテンツ（JSON配列）',
  CREATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  CREATE_USER VARCHAR(40) COMMENT '作成ユーザー',
  LAST_UPDATE_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最終更新日時',
  LAST_UPDATE_USER VARCHAR(40) COMMENT '最終更新ユーザー',
  PRIMARY KEY (MESSAGE_ID),
  UNIQUE KEY UK_CONV_MSG_SEQ (CONVERSATION_ID, MESSAGE_SEQ),
  INDEX IDX_CONV_MESSAGE (CONVERSATION_ID),
  CONSTRAINT FK_MESSAGE_CONVERSATION FOREIGN KEY (CONVERSATION_ID)
    REFERENCES T_CHAT_CONVERSATION(CONVERSATION_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AIチャットメッセージ'
"""

# テーブル存在確認用
CHECK_TABLE_EXISTS = """
SELECT COUNT(*) as count
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = %s
"""
